# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: .gitpod/Dockerfile

tasks:
    - before: mkdir -p build && cd build
      init: cmake -G"Ninja" ..
      command: ninja
